import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: "Nadun",
      email: "admin@example.lk",
      nic: "199934312655",
      age: 21,
      address: "Godagama",
      number: "0714185516",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    }
  ],
  doctors: [
    {
      
      name: "sulthan",
      category: "Dentist",
      image: "/images/img.jpg",
      price: 120,
      bookingAvailable: 10,
      specialty: "Dentist",
      rating: 4.5,
      numReviews: 10,
      description: "Best Doctor available",
    },
    {
      name: "balthan",
      category: "Dentist",
      image: "/images/img.jpg",
      price: 120,
      bookingAvailable: 10,
      specialty: "Dentist",
      rating: 4.5,
      numReviews: 10,
      description: "Best Doctor available",
    },
    {
      name: "kalthan",
      category: "Dentist",
      image: "/images/img.jpg",
      price: 120,
      bookingAvailable: 10,
      specialty: "Dentist",
      rating: 4.5,
      numReviews: 10,
      description: "Best Doctor available",
    },
    {
      name: "niltha",
      category: "Dentist",
      image: "/images/img.jpg",
      price: 120,
      bookingAvailable: 0,
      specialty: "Dentist",
      rating: 4.5,
      numReviews: 10,
      description: "Best Doctor available",
    },
    {
      name: "kilthan",
      category: "Dentist",
      image: "/images/img.jpg",
      price: 120,
      bookingAvailable: 5,
      specialty: "Dentist",
      rating: 4.5,
      numReviews: 10,
      description: "Best Doctor available",
    },
    {
      name: "sulthani",
      category: "nalthan",
      image: "/images/img.jpg",
      price: 120,
      bookingAvailable: 0,
      specialty: "Dentist",
      rating: 4.5,
      numReviews: 10,
      description: "Best Doctor available",
    },
  ],
};
export default data;
